# Package Overview
package_name: phishing_detection_model

pipeline_name: phishing_detection_model
pipeline_save_file: phishing_detection_model_output_v

# Data Files
training_data_file: train.csv
test_data_file: test.csv

# Variables
# The variable we are attempting to predict
target: Label

features: URL

# set train/test split
test_size: 0.2

# to set the random seed
random_state: 0

# Regularization parameter
alpha: 0.001
