name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  tests:
    name: "Test and lint for Python ${{ matrix.python-version }}"
    runs-on: "windows-latest"

    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade virtualenv tox tox-gh-actions
      - name: "Run tests for ${{ matrix.python-version }}"
        run: tox -e test_package
      - name: "Run linters (isort, black, mypy and flake8) for ${{ matrix.python-version }}"
        run: tox -e lint
